### ISSUE TITLE
Add support for GetObjectAttributesRequest(ObjectAttributes.OBJECT_PARTS)

### ISSUE THREAD

**Issue by campidelli** [adobe/S3Mock#1227] opened 2023-07-11 23:06 UTC
Hi,

So, my use case is to use pre-signed URLs for multipart downloads. And there are two ways to perform those downloads:

1. If the object has been uploaded as multipart, I generate the URL with the query parameter `partNumber=N`;
2. If not, I use the header `Range: bytes=X-Y`.

To determine which one shall be used I check for `GetObjectAttributesRequest(ObjectAttributes.OBJECT_PARTS)` and if the parts are `null` then I use `ObjectAttributes.OBJECT_SIZE` to determine the byte range.

I am currently using version `2.16.0` which supports `ObjectAttributes.OBJECT_SIZE` already, thanks for that, but I also need a way to know whether it is a multipart upload.

Cheers!

**Comment by afranken** [comment] 2023-07-12 09:47
related to #536

**Comment by afranken** [comment] 2023-07-12 10:32
@campidelli 
Do you have a working test case against the real S3 API?
When I was implementing #536, I couldn't figure out how the parts are supposed to work. Citing myself:

> The implementation for the "HeadObject" attributes is straightforward, but I struggle to understand how the "ListParts" attributes are supposed to work.
> 
> I can't get a test case against the S3 API to work.
> There is no way to pass in an "uploadId", so a call to an object where the multipart upload is still running returns a 404 key not found.
> After the multipart upload is completed, the "parts" in the response are empty because there are no more parts.

**Comment by campidelli** [comment] 2023-07-13 04:29
This is a use case https://github.com/campidelli/file-storage-service/blob/main/src/test/java/campidelli/file/storage/AsyncMultipartDownloadIIntegrationTest.java#L66

BTW, I have found more things in this new version:

1. Now I need to provide basic credentials to my S3Client, the `DefaultCredentialsProvider` doesn't work anymore.
2. When I use `.withVolumeAsRoot(TEMP_DIR.getAbsolutePath())` it times out looking for `/favicon.ico` and the test doesn't run.

**Comment by afranken** [comment] 2023-07-17 17:27
@campidelli just to reiterate: 
this application and the tests are working as-is against the real S3 backend? 
After looking at the code, I'm pretty sure they will not.

There are multiple problems with the test setup, none have anything to do with S3Mock:
* The application can't reach the S3Mock testcontainer.
* The WebTestClient request timeout is so low (5 seconds) that if the application can reach S3(Mock) and makes multiple requests, we run into timeouts.
* The file uploaded is so small that the S3Client uses a "putObject" instead of a MultipartUpload. 
* The part size calculation is wrong, object size is always returned in bytes, so parts are expected to be 8 bytes long in your implementation.
* Since MultipartUpload is not used, getObjectAttributes returns all needed properties in the response.
...

Please make sure that your code works before asking me to debug problems in S3Mock. I'm doing this in my free time... ;)

Also: run S3Mock as an external process / Docker container to see the logs. Make sure to use the "debug" setting. You can see which requests come in, which controller methods they are being routed to etc. Using "trace" gives even more output, though that may be hard to read - Spring logs a lot on "trace".
You'd have seen that there are no errors in the logs, getObjectAttributes is never called and the problem is within your test and application.

https://github.com/campidelli/file-storage-service/pull/3

**Comment by afranken** [comment] 2023-07-18 10:50
Also:
`DefaultCredentialsProvider` is provided by the AWS SDK. In your test application, I can see in the debugger that `DefaultCredentialsProvider` is used and works, and `withVolumeAsRoot` does not throw an error when used.
Not sure how you can reproduce these problems.

> This is a use case https://github.com/campidelli/file-storage-service/blob/main/src/main/java/campidelli/file/storage/controller/AsyncMultipartDownloadController.java
> 
> BTW, I have found more things in this new version:
> 
>     1. Now I need to provide basic credentials to my S3Client, the `DefaultCredentialsProvider` doesn't work anymore.
> 
>     2. When I use `.withVolumeAsRoot(TEMP_DIR.getAbsolutePath())` it times out looking for `/favicon.ico` and the test doesn't run.

**Comment by afranken** [comment] 2023-08-18 12:16
@campidelli I'll close this ticket.
If you have any more questions / challenges then re-open or open a new issue with a reproducer I can easily execute :)

**Closed by afranken** 2023-08-18 12:16 UTC
Labels: feature
