### ISSUE TITLE
Bug: AmazonS3.listObjects(ListObjectsRequest) result does not include exact match of prefix

### ISSUE THREAD

**Issue by AplusKminus** [adobe/S3Mock#227] opened 2020-06-30 08:10 UTC
**Assume the following file structure:**
bkt\\
bkt\foo\bar\\
bkt\foo\bar\baz\\
bkt\foo\bar.txt

Now execute the following code, given `amazonS3`:
```java
var listRq = new ListObjectsRequest();
listRq.setBucketName("bkt");
listRq.setPrefix("foo/bar/");

var listing = amazonS3.listObjects(listRq);
System.out.println(listing.getObjectSummaries()
            .stream()
            .map(S3ObjectSummary::getKey)
            .collect(Collectors.joining(", ")));
```
## Expected Behavior
Executing this against S3 results in:
```
foo/bar/, foo/bar/baz/
```
## Observed Behavior
Executing this against S3Mock results in:
```
foo/bar/baz/
```
### Version Details
s3Mock version used: 2.1.20 (edit: also tested with 2.1.22)
AWS S3 SDK version: 1.11.579 (this version is the last where S3Mock integration tests run inside IntelliJ for us)

**Comment by outsideMyBox** [comment] 2020-11-19 10:25
I have a similar issue in my unit tests without defining prefixes.
Here is a snippet:

```java
@ClassRule
public static final S3MockRule S3_MOCK_RULE = S3MockRule.builder().silent().withHttpPort(S3_PROVIDER_PORT).build();

protected AmazonS3 s3Client = S3_MOCK_RULE.createS3Client(S3_PROVIDER_REGION);

@Before
public void init() {
  s3Client.listBuckets().forEach(b -> purgeBucket(s3Client, b));
  s3Client.createBucket(BR_BUCKET_NAME);
}

@Test
public void test1() {
     ... // Creates 3 objects.
    var listing = s3Client.listObjects("mybucket");  // OK, return 3.
}

@Test
  public void test2() {
     ... // Creates 3 objects.
    var listing1 = s3Client.listObjects("mybucket"); // Returns 3 if run individually but 2 if run after test1().
    var listing2 = s3Client.listObjects("mybucket"); // Always returns 3 (even when the previous list returns 2)
}

```
Note that the isTruncated() returns false each time so that is not the issue here.

**Comment by afranken** [comment] 2021-07-01 14:15
@outsideMyBox 
can't reproduce your problem locally after adding your code (plus setup plus "purge bucket") to the `com.adobe.testing.s3mock.junit4.S3MockRuleTest`

```
  @Before
  public void init() {
    s3Client.listBuckets().forEach(b -> purgeBucket(
        s3Client.listObjects(b.getName()).getObjectSummaries()
            .stream()
            .map(S3ObjectSummary::getKey)
            .collect(Collectors.toList()))
    );
    s3Client.createBucket(BUCKET_NAME);
  }

  @Test
  public void test1() {
    createFiles(UPLOAD_FILE_NAME, 3);
    ObjectListing listing = s3Client.listObjects(BUCKET_NAME);  // OK, return 3.
    assertThat(listing.getObjectSummaries().size(), is(3));
  }

  @Test
  public void test2() {
    createFiles(UPLOAD_FILE_NAME, 3);
    ObjectListing listing1 = s3Client.listObjects(BUCKET_NAME); // Returns 3 if run individually but 2 if run after test1().
    assertThat(listing1.getObjectSummaries().size(), is(3));
    ObjectListing listing2 = s3Client.listObjects(BUCKET_NAME); // Always returns 3 (even when the previous list returns 2)
    assertThat(listing2.getObjectSummaries().size(), is(3));
  }

  private void purgeBucket(List<String> keys) {
    // Delete the sample objects.
    DeleteObjectsRequest multiObjectDeleteRequest = new DeleteObjectsRequest(BUCKET_NAME)
        .withKeys(keys
            .stream()
            .map(DeleteObjectsRequest.KeyVersion::new)
            .collect(Collectors.toList())
        )
        .withQuiet(false);
    // Verify that the objects were deleted successfully.
    DeleteObjectsResult delObjRes = s3Client.deleteObjects(multiObjectDeleteRequest);
    int successfulDeletes = delObjRes.getDeletedObjects().size();
    assertThat(successfulDeletes, is(keys.size()));
  }

  private void createFiles(String name, int count) {
    for (int i = 0; i < count; i++) {
      createFile(name, i + name);
    }
  }

  private void createFile(String fileName, String keyName) {
    final File uploadFile = new File(fileName);
    s3Client.putObject(new PutObjectRequest(BUCKET_NAME, keyName, uploadFile));
  }
```

the listobjects calls always work and return the correct count.
So I can only guess what the problem is - maybe a timing issue? 

If your problem persists, then please open a _new_ issue linking a working unit-test, for instance in your fork of this repository, or an empty repository where we can run the test with maven or gradle.

**Comment by afranken** [comment] 2022-01-16 13:48
closing since nobody replied and I can't reproduce this.
I made several refactorings in 2021 to the way we escape incoming bucket names, keys, delimiters and prefixes, so I guess I fixed this along with several other issues complaining about (non-) matching keys and prefixes / delimiters.

**Closed by afranken** 2022-01-16 13:48 UTC
