### ISSUE TITLE
Using prefix filter doesn't give the same result as aws

### ISSUE THREAD

**Issue by johnbridstrup** [adobe/S3Mock#653] opened 2022-06-22 21:12 UTC
I'm trying to test an AWS lambda function written in python using s3 mock. I'm using the `boto3` library. I am getting differing behavior between real s3 and s3mock that is probably a pretty simple fix, although I haven't looked into the source.

When I run
```
s3_resource = boto3.Session().resource(service_name="s3", **other_kwargs)

objects = list(s3_resource.Bucket(bucket_name).objects.filter(Prefix="prefix/")

logger.debug([obj.key for obj in objects])
```

I get, in s3mock:
`['prefix/file1', 'prefix/file2', ...]`

and in aws:
`['prefix/', 'prefix/file1', 'prefix/file2', ...]`

Seems like it's probably due to s3mock being a normal filesystem while s3 doesn't actually have folders. Just wanted to point this difference in behavior out.

**Comment by afranken** [comment] 2022-07-25 12:20
@johnbridstrup sorry for the delay, I was on vacation.

Just tried this on a live S3 bucket. 
For me, only the objects containing the prefix in the name are listed, not the prefix itself.

The same is true if I use the AWS CLI:
`aws s3api list-objects-v2 --bucket <bucketname> --prefix <prefixname>`
Only the objects are listed, not the prefix.

Looking at the documentation, it's a bit ambiguous and none of the examples match this use-case:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html
So it's hard to say wheterh the prefix itself is ever included in the API response or not.

----

How do you create the objects?
Are you creating the prefix `prefix/` as an object in S3 prior to your listing?
Maybe that would explain the difference - in my bucket, all objects are created including the prefix in the name, but the prefix itself was not created in S3...

**Comment by afranken** [comment] 2022-09-03 10:57
@johnbridstrup 
Closing, can't reproduce, see above. 

If you can provide a full code example to reproduce the error above, I'm happy to look into this again.

**Closed by afranken** 2022-09-03 10:57 UTC
Labels: invalid
