### ISSUE TITLE
[Question] - Why checking if bucket exists?

### ISSUE THREAD

**Issue by resilva87** [adobe/S3Mock#156] opened 2019-06-21 17:17 UTC
Hi,

While investigating some issues with S3Mock I've noticed that the `putObject` method in `FileStoreController` first checks if the bucket exists (https://github.com/adobe/S3Mock/blob/master/server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java#L488) before handling the operation.

But the method `putS3Object` in `FileStore` component, which is called afterwards, can handle any missing bucket by creating it (https://github.com/adobe/S3Mock/blob/master/server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java#L249)

I wonder what is the reason to really check if the bucket exists before proceeding?

**Comment by Xivolkar** [comment] 2019-07-11 15:02
@resilva87 Best guess - to simulate missing bucket on S3?

**Comment by agudian** [comment] 2019-07-11 15:43
Sorry for the long delay, it fell off my radar:

The current behavior is as intended, as the real S3 doesn't create missing buckets on the fly, either. The `getBucketOrCreateNewOne` method is most certainly a left-over from when we didn't have the check, yet.

I'm closing this, but if you'd like to continue the discussion, feel free to reopen.

**Closed by agudian** 2019-07-11 15:43 UTC
