### ISSUE TITLE
Inconsistent file name encoding

### ISSUE THREAD

**Issue by scooper91** [adobe/S3Mock#119] opened 2019-01-25 11:06 UTC
We've noticed some inconsistent behaviour when dealing with objects with spaces in the key.  These are all tested through the JS AWS SDK.

1. `putObject` `key: some file`. Stored on disk as `some%20file`
2. `listObjectsV2`. `some file` is retrieved as `some%20file`

When listing objects from the real S3, the key is returned as `some file`, not `some%20file`.

There are inconsistencies in the behaviour of `deleteObject` vs `deleteObjects` when the keys have spaces:

`deleteObject`:
 - Key `some file`: object is deleted
 - Key `some%20file`: object is not deleted

`deleteObjects`:
 - Key `some%20file`: object is deleted
 - Key `some file`: object is not deleted

**Comment by alinpa** [comment] 2019-02-01 17:35
Hello, 

I have the same issue. The s3mock doesn't work correctly for the [Characters That Might Require Special Handling ](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys) those characters are not supported. 
I think the problem is in: com.adobe.testing.s3mock.FileStoreController class.
The filenameFrom method has an issue.
`private static String filenameFrom(final @PathVariable String bucketName,
      final HttpServletRequest request) {
    final String requestUri = request.getRequestURI();
    return requestUri.substring(requestUri.indexOf(bucketName) + bucketName.length() + 1);
  }`
The problem is that: The file name must be decoded, because can contain special chars.

The solution is the following: 

 return UrlEncoded.decodeString(requestUri.substring(requestUri.indexOf(bucketName) + bucketName.length() + 1));

How can we have this on master?

**Comment by agudian** [comment] 2019-02-19 11:58
Fixed with #129 by @alinpa 👍

**Closed by agudian** 2019-02-19 11:58 UTC

**Comment by agudian** [comment] 2019-02-19 12:17
@alinpa release `2.1.3` is on Docker-Hub and on its way to Maven Central (give it some minutes to sync).
