### ISSUE TITLE
Keys are encoded in the response

### ISSUE THREAD

**Issue by kolyanu4** [adobe/S3Mock#199] opened 2019-11-29 11:28 UTC
Hi, I'm using your image for tests. After 2.1.17 I found the issue that bucket is not deleted anymore. That happens cause in 2.1.16 it was deleted ignoring if there were files or not.

After some checks I found that files are not deleted cause keys are encoded in the response and when you call `delete` the keys cannot be found.

Current behavior:
```
# docker run -p 9091:9090 --name test_s3 adobe/s3mock:2.1.17
In [37]: from io import BytesIO 
    ...:  
    ...: import boto3 
    ...:  
    ...: endpoint_url = 'http://localhost:9091' 
    ...: bucket_name = 'test_bucket' 
    ...: test_keys = ['test_key', 'тест'] 
    ...:  
    ...: s3 = boto3.resource('s3', endpoint_url=endpoint_url) 
    ...: s3.create_bucket(Bucket=bucket_name) 
    ...: bucket = s3.Bucket(bucket_name) 
    ...:  
    ...: for test_key in test_keys: 
    ...:     csv_file = BytesIO(b'John,Doe,120 jefferson st.,Riverside, NJ, 08075') 
    ...:     bucket.put_object(Body=csv_file, Key=test_key) 
    ...:  
    ...: objects = bucket.objects.all() 
    ...: print(list(objects))                                                                                           
[s3.ObjectSummary(bucket_name='test_bucket', key='test%5Fkey'), s3.ObjectSummary(bucket_name='test_bucket', key='%D1%82%D0%B5%D1%81%D1%82')]
```

Expected behavior:
```
# aws s3
In [38]: from io import BytesIO 
    ...:  
    ...: import boto3 
    ...:  
    ...: bucket_name = 'test-example-aws' 
    ...: test_keys = ['test_key', 'тест'] 
    ...:  
    ...: s3 = boto3.resource('s3') 
    ...: bucket = s3.Bucket(bucket_name) 
    ...:  
    ...: for test_key in test_keys: 
    ...:     csv_file = BytesIO(b'John,Doe,120 jefferson st.,Riverside, NJ, 08075') 
    ...:     bucket.put_object(Body=csv_file, Key=test_key) 
    ...:  
    ...: objects = bucket.objects.all() 
    ...: print(list(objects)) 
    ...:                                                                                                                
[s3.ObjectSummary(bucket_name='test-example-aws', key='test_key'), s3.ObjectSummary(bucket_name='test-example-aws', key='тест')]
```

**Comment by timoe** [comment] 2019-11-29 13:57
Thanks for reporting this. Seems to be a bug.

**Comment by timoe** [comment] 2019-11-29 14:37
could not reproduce that with tests e.g. from `AmazonClientUploadIT`. I'll try to get your python example running

**Comment by oofoghlu** [comment] 2021-03-25 18:59
I've encountered this problem with boto3 when listing objects in a bucket e.g. with boto3 s3 client: `client.list_objects_v2(Bucket=BUCKET)`

I think I know what the problem is. boto3 will automatically send EncodingType='url' if none is specified. It should then automatically decode the url encoding when returning the response dict.

I think the reason it is not performing the decode is because S3Mock isn't sending `EncodingType` in the responses. This is expected in the response when it is requested as per https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax.

**Comment by agudian** [comment] 2021-04-23 14:36
Fixed by @froesef 👍

**Closed by agudian** 2021-04-23 14:36 UTC
Labels: bug
