### ISSUE TITLE
aws sync broken since 2.1.29

### ISSUE THREAD

**Issue by mibollma** [adobe/S3Mock#257] opened 2021-06-09 12:27 UTC
aws sync seems to be broken since 2.1.29. 
Calling the command in it's basic form e.g. `aws s3 sync . s3://bucket --endpoint-url http://localhost:9090` produces the error **fatal error: 'Prefix'**.
The same command works fine till version 2.1.28.

**Comment by afranken** [comment] 2021-06-28 11:52
I just reproduced this locally.
In #251, which was released in 2.1.29, support for the "encodingType" parameter was added.

Unfortunately, this seems to have broken object listing, as the client expects several field values in the response to be encoded (`Prefix` for example). If the field value is empty, the client expects those fields to be dropped from the response.
The error is thrown because we always return the `Prefix` and `CommonPrefix` fields with empty values, which the client tries to decode without checking if the value is empty.

**Comment by afranken** [comment] 2021-06-28 11:52
API for reference:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax

**Comment by gerhalt** [comment] 2021-06-29 21:30
Ran into exactly the same original URL-encoding issue and the new breakage described here.

**Comment by afranken** [comment] 2021-06-30 10:11
I have a fix ready, just working on the tests right now - unfortunately the V1 and V2 APIs (or rather the client implementation of ListObjects vs ListObjectsV2) do different things when it comes to responses with encoding.

I'm wondering if we have to keep supporting the V1 APIs in the mock...

**Comment by mibollma** [comment] 2021-06-30 10:40
I'm still using V1 currently. One reason is that some features were only available in V1 at least until recently, such as DynamoDB client-side encryption: https://github.com/aws/aws-sdk-java-v2/issues/34#issuecomment-859703909.

**Comment by afranken** [comment] 2021-06-30 14:13
I did not mean the Java SDK V1, but the API:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html

It is possible to request both ListObjects as well as ListObjectsV2 with the V1 SDK:
V1
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3.java#L543
V2
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3.java#L552

**Closed** 2021-07-01 07:07 UTC
Labels: bug
