### ISSUE TITLE
AmazonS3: No valid region has been specified. Unable to return region name

### ISSUE THREAD

**Issue by ivaleev** [adobe/S3Mock#207] opened 2020-01-24 12:12 UTC
Getting an exception:
`java.lang.IllegalStateException: No valid region has been specified. Unable to return region name
at com.amazonaws.services.s3.AmazonS3Client.getRegionName(AmazonS3Client.java:4613)
`

added one line to provided test S3MockRuleTest:
https://github.com/adobe/S3Mock/blob/master/testsupport/junit4/src/test/java/com/adobe/testing/s3mock/junit4/S3MockRuleTest.java

`    @Test
    public void shouldUploadAndDownloadObject() throws Exception {
        final File uploadFile = new File(UPLOAD_FILE_NAME);

        s3Client.createBucket(BUCKET_NAME);
        s3Client.putObject(new PutObjectRequest(BUCKET_NAME, uploadFile.getName(), uploadFile));

        final S3Object s3Object = s3Client.getObject(BUCKET_NAME, uploadFile.getName());

        System.out.println(s3Client.getRegionName() + s3Client.getRegion());`

**Comment by timoe** [comment] 2020-01-25 07:44
That's not a bug I guess. 
`com.amazonaws.services.s3.AmazonS3Client#getRegionName` tries to match the endpoint (localhost in our case) against `"s3[-.]([^.]+)\\.amazonaws\\.com(\\.[^.]*)?"`.

Obviously this won't match so 
```
        Matcher m = Region.S3_REGIONAL_ENDPOINT_PATTERN.matcher(authority);
        try {
            m.matches();
            return RegionUtils.getRegion(m.group(1)).getName();
```

will throw an IllegalArgumentException. Same applies to `getRegion`.

What do you think?

**Comment by ivaleev** [comment] 2020-01-25 21:16
Yes, I see.
Unfortunately, I had to change the production code to make my tests pass. The region was taken from s3client in the production code.
I had to pass the region to the class constructor.

**Comment by afranken** [comment] 2022-07-27 14:15
looks like this question has been answered a while back, closing :)

**Closed by afranken** 2022-07-27 14:15 UTC
Labels: question
